const ACTION_TYPES = {
    COUNTER_ADD: 'COUNTER_ADD',
    COUNTER_SUB: 'COUNTER_SUB',
    COUNTER_SET_STEP: 'COUNTER_SET_STEP',

    SET_THEME: 'SET_THEME',
    //user
    CREATE_USER: 'CREATE_USER',
    READ_USER: ' READ_USER',
    UPDETE_USER: ' UPDETE_USER',
    DELETE_USER: 'DELETE_USER',

    //user info
    GET_USER_ACTION: 'GET_USER_ACTION',
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_ERROR: 'GET_USER_ERROR',

    //info superhero
    GET_SUPERHERO_LIST: 'GET_SUPERHERO_LIST',


    //custom counter
    CUSTOM_INCR: 'CUSTOM_INCR',
    CUSTOM_DECR: 'CUSTOM_DECR',
    CUSTOM_SET_VALUE: 'CUSTOM_SET_VALUE',

    

};
export default ACTION_TYPES;